[package]
name = "bq-rs"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "bq-rs"
path = "src/main.rs"

[workspace]
members = [ "crates/*" ]

[dependencies]
gauth = { path = "crates/gauth" }
clap = { version = "4.4.8", features = ["derive"] }