[package]
name = "bq-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "bq-rs"
path = "src/main.rs"

[workspace]
members = [ "crates/*" ]

[dependencies]
gauth = { path = "crates/gauth" }
clap = { version = "4.4.8", features = ["derive"] }
ureq = "2.9.0"
serde = {version = "1.0.192", features = ["serde_derive"]}
serde_json = "1.0.108"