version: '3.8'

services:
  bigquery-emulator:
    image: ghcr.io/goccy/bigquery-emulator:latest
    ports:
      - '9050:9050'
    command: ['--project=test']
    platform: linux/x86_64
    tty: true
    stdin_open: true
