[package]
name = "gauthenticator"
version = "0.1.1"
edition = "2021"
authors = ["Isaac Adams <isaac.d.adams@gmail.com>"]
license = "MIT OR Apache-2.0"
description = """
Simple API for authenticating with google services

```rust
let sa = gauthenticator::load("./service-account-key.json".as_ref()).unwrap();
let token = sa.access_token().unwrap();
```

Project homepage: https://github.com/isaacadams/bq-rs
"""
homepage = "https://github.com/isaacadams/bq-rs"
repository = "https://github.com/isaacadams/bq-rs"
keywords = ["gcp", "google", "authentication"]

[lib]
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.20"
serde = {version = "1.0.192", features = ["serde_derive"]}
serde_json = "1.0.108"
chrono = { version = "0.4.31", features = ["serde"]}
dotenvy = "0.15.7"
base64 = "0.21.5"
rustls = "0.21.9"
rustls-pemfile = "1.0.4"
thiserror = "1.0.50"
